// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF5r0N2u8KVFILABFMCtNbF7w4VtmQy54',
    appId: '1:516104758418:web:81dd90f1624515f8f6f24b',
    messagingSenderId: '516104758418',
    projectId: 'pibo-aac5a',
    authDomain: 'pibo-aac5a.firebaseapp.com',
    databaseURL: 'https://pibo-aac5a-default-rtdb.firebaseio.com',
    storageBucket: 'pibo-aac5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAuhyHCe2unXy4DxDr4GhMMMjpXJON21o',
    appId: '1:516104758418:android:88c683e89ffa6a9ef6f24b',
    messagingSenderId: '516104758418',
    projectId: 'pibo-aac5a',
    databaseURL: 'https://pibo-aac5a-default-rtdb.firebaseio.com',
    storageBucket: 'pibo-aac5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrOP7MgAbBORrLm6Y9AiY-kufQPsKL3PQ',
    appId: '1:516104758418:ios:863be6ac3ebee8e5f6f24b',
    messagingSenderId: '516104758418',
    projectId: 'pibo-aac5a',
    databaseURL: 'https://pibo-aac5a-default-rtdb.firebaseio.com',
    storageBucket: 'pibo-aac5a.appspot.com',
    iosClientId: '516104758418-k5d4mhf5k1iujf5j3hhj89d36b97o3p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pibo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrOP7MgAbBORrLm6Y9AiY-kufQPsKL3PQ',
    appId: '1:516104758418:ios:863be6ac3ebee8e5f6f24b',
    messagingSenderId: '516104758418',
    projectId: 'pibo-aac5a',
    databaseURL: 'https://pibo-aac5a-default-rtdb.firebaseio.com',
    storageBucket: 'pibo-aac5a.appspot.com',
    iosClientId: '516104758418-k5d4mhf5k1iujf5j3hhj89d36b97o3p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pibo',
  );
}
